#!/usr/bin/python
# -*- coding: utf-8 -*-

# -- DO NOT EDIT THIS FILE --
# This file is -not- to be edited by hand.  It is simply defaults.
# Actual configuration should be done in config.xml in the root directory.
# -- DO NOT EDIT THIS FILE --

class Configuration:
    debug = False
    
    serverId = "localhost"
    serverAdmin = "admin@localhost"
    serverName = "SMS77.de SMS-Gateway"
    serverDescription = "A xmpp-gateway for sms over sms77.de"
    
    jabberHost = "localhost"
    jabberPort = 5347
    jabberComponentName = "sms77.localhost"
    jabberPassword = "secret"
    
    mysqlHost = "localhost"
    mysqlDatabase = "sms77"
    mysqlUsername = "sms77"
    mysqlPassword = "secret"
    
    inboundInterface = "localhost"
    inboundPort = 8888
    
    contactIcon = None
    contactIconHash = None
    
def init():
    global config
    config = Configuration()

def getConfig():
    return config
